SECRET_KEY = ''

ALLOWED_HOSTS = []

DB_ENGINE = ''
DB_NAME = ''
DB_USER = ''
DB_PASSWORD = ''
DB_HOST = ''
DB_PORT = ''

ES_HOST = ''
ES_USER = ''
ES_PASSWORD = ''

EMAIL_BACKEND = ''
AWS_ACCESS_KEY_ID = '' 
AWS_SECRET_ACCESS_KEY = '' 
AWS_SES_REGION = ''


# LOCAL
CAPTCHA_SITE_KEY = ''
CAPTCHA_SECRET = ''


USE_S3 = 'False'
#AWS_ACCESS_KEY_ID = your_access_key_id
#AWS_SECRET_ACCESS_KEY = your_secret_access_key
AWS_STORAGE_BUCKET_NAME = ''
AWS_S3_CUSTOM_DOMAIN = ''
AWS_DEFAULT_ACL = ''
AWS_S3_OBJECT_PARAMETERS = {}
AWS_LOCATION = ''

STATIC_URL = ''
STATICFILES_STORAGE = ''
PUBLIC_MEDIA_LOCATION = ''
MEDIA_URL = ''
DEFAULT_FILE_STORAGE = ''