# Generated by Django 3.2.3 on 2021-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoli',
            fields=[
                ('id_scoala', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=80)),
                ('tip', models.CharField(max_length=45)),
                ('universitate', models.CharField(blank=True, max_length=80, null=True)),
                ('localitate', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'scoli',
                'managed': False,
            },
        ),
    ]
