"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

try:
    import config
except ModuleNotFoundError:
    import config_example as config
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.core.mail',
    'storages',
    'prof',
    'search',
    'school',
    'site_utility',
    'user',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        os.path.join(BASE_DIR, 'search/templates'), 
        os.path.join(BASE_DIR, 'prof/templates'), 
        os.path.join(BASE_DIR, 'templates'),
        os.path.join(BASE_DIR, 'school/templates'),
        os.path.join(BASE_DIR, 'user/templates'),
        os.path.join(BASE_DIR, 'site_utility/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# LOCAL TESTING - COMMEN WHEN USING ON DEV OR PROD SERVER
DATABASES = {
    'default': {
        'ENGINE': config.DB_ENGINE,
        'NAME': config.DB_NAME,
        'USER': config.DB_USER,
        'PASSWORD': config.DB_PASSWORD,
        'HOST': config.DB_HOST,
        'PORT': config.DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'user:login'


###### CUSTOM ADDED CODE ########


######### ELASTIC SEARCH #########

ES_HOST = config.ES_HOST
ES_USER = config.ES_USER
ES_PASSWORD = config.ES_PASSWORD


# # AMAZON EMAIL SES

EMAIL_BACKEND = config.EMAIL_BACKEND
AWS_ACCESS_KEY_ID = config.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = config.AWS_SECRET_ACCESS_KEY
AWS_SES_REGION = config.AWS_SES_REGION


########## CAPTCHA SETUP ##########

CAPTCHA_SITE_KEY = config.CAPTCHA_SITE_KEY
CAPTCHA_SECRET = config.CAPTCHA_SECRET

########## STORAGES ############


if config.USE_S3 == 'True':
    USE_S3 = config.USE_S3
    #AWS_ACCESS_KEY_ID = your_access_key_id
    #AWS_SECRET_ACCESS_KEY = your_secret_access_key
    AWS_STORAGE_BUCKET_NAME = config.AWS_STORAGE_BUCKET_NAME
    AWS_S3_CUSTOM_DOMAIN = config.AWS_S3_CUSTOM_DOMAIN
    AWS_DEFAULT_ACL = config.AWS_DEFAULT_ACL
    AWS_S3_OBJECT_PARAMETERS = config.AWS_S3_OBJECT_PARAMETERS
    AWS_LOCATION = config.AWS_LOCATION

    STATIC_URL = config.STATIC_URL
    STATICFILES_STORAGE = config.STATICFILES_STORAGE
    PUBLIC_MEDIA_LOCATION = config.PUBLIC_MEDIA_LOCATION
    MEDIA_URL = config.MEDIA_URL
    DEFAULT_FILE_STORAGE = config.DEFAULT_FILE_STORAGE
else:
    # LOCAL STATIC FOLDER
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]

