# Generated by Django 3.2.3 on 2021-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=45)),
                ('institutie', models.CharField(max_length=80)),
                ('localitate', models.CharField(max_length=45)),
                ('titlu', models.CharField(blank=True, max_length=45, null=True)),
                ('materie', models.IntegerField(blank=True, null=True)),
                ('departament', models.CharField(blank=True, max_length=80, null=True)),
                ('universitate', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'profesori',
                'managed': False,
            },
        ),
    ]
